const locations = [
    // Districts
    {
        name: "Anantapur",
        type: "district",
        description: "Known for its historical temples and drought-resistant agriculture",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/15th_century_Bugga_Ramalingeswara_temple%2C_Tadipatri%2C_Andhra_Pradesh%2C_India_-_193.jpg",
    },
    {
        name: "Chittoor",
        type: "district",
        description: "Home to the famous Tirupati temple and Horsley Hills",
        imageUrl: "https://resources.thomascook.in/images/holidays/sightSeeing/chittoor.jpeg ",
    },
    {
        name: "East Godavari",
        type: "district",
        description: "Known as the 'Rice Bowl of Andhra Pradesh'",
        imageUrl: "https://images.unsplash.com/photo-1642182887529-df52def152b6?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
        name: "Guntur",
        type: "district",
        description: "Famous for chili cultivation and historical sites",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaRJlC6djquAhD2v6P5YyT-We7oKtLbfnsbQ&s",
    },
    {
        name: "Krishna",
        type: "district",
        description: "Cultural hub with Vijayawada as its headquarters",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYkz4N3jT37zMCWX5-h64mytFhV7F2zjQnVw&s",
    },
    {
        name: "Kurnool",
        type: "district",
        description: "Historical capital of Andhra State",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Kurnool_fort%2CAP_-_panoramio.jpg",
    },
    {
        name: "Prakasam",
        type: "district",
        description: "Known for its extensive coastline",
        imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/b5/db/4f/prakasam-barrage.jpg?w=1200&h=-1&s=1",
    },
    {
        name: "Nellore",
        type: "district",
        description: "Famous for aquaculture and temples",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxyXra03NZX3NHHVQLCG8SDc3uURUdO1XaGg&s",
    },
    {
        name: "Srikakulam",
        type: "district",
        description: "Rich in Buddhist heritage",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBK7lxQE1qjz4BYr1LdZ1ukRVd3j_v1lcohA&s",
    },
    {
        name: "Visakhapatnam",
        type: "district",
        description: "Major port city with beautiful beaches",
        imageUrl: "https://s7ap1.scene7.com/is/image/incredibleindia/visakhapatnam-andhra-pradesh-city-2-hero?qlt=82&ts=1726744436128",
    },
    {
        name: "Vizianagaram",
        type: "district",
        description: "Known for its historical fort",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5FhDEL8rCeP3NH6JzkfkGBRhUXi-hmGsAIg&s",
    },
    {
        name: "West Godavari",
        type: "district",
        description: "Known as 'Rice Bowl of India'",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGuYisfsTNIQOxYqA4xjVkZFLJEcyGWAb4UQ&s",
    },
    {
        name: "YSR Kadapa",
        type: "district",
        description: "Rich in mineral resources",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/200_years_memorable_pylon.jpg",
    },

    // Famous Places
    {
        name: "Tirumala Temple",
        type: "religious",
        district: "Chittoor",
        description: "World's richest temple dedicated to Lord Venkateswara",
        imageUrl: "https://images.unsplash.com/photo-1741003412854-bd4b264c4af3?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
        name: "Araku Valley",
        type: "natural",
        district: "Visakhapatnam",
        description: "Beautiful hill station known for coffee plantations",
        imageUrl: "https://images.unsplash.com/photo-1717585163315-02e3f0a96584?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGFyYWt1JTIwdmFsbGV5fGVufDB8fDB8fHww",
    },
    {
        name: "Lepakshi Temple",
        type: "historical",
        district: "Anantapur",
        description: "Ancient temple with remarkable mural paintings",
        imageUrl: "https://images.unsplash.com/photo-1701121696225-7bbcd7877a46?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
        name: "Borra Caves",
        type: "natural",
        district: "Visakhapatnam",
        description: "Deepest caves in India with stunning formations",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQieG3jBCgtRNcNYTgscOCGe4FiukjwudJjOg&s",
    },
    {
        name: "Undavalli Caves",
        type: "historical",
        district: "Guntur",
        description: "4-story cave temples carved out of solid sandstone",
        imageUrl: "https://magikindia.com/wp-content/uploads/2026/06/undavalli-caves-4-1024x683.jpg",
    },
    {
        name: "Gandikota",
        type: "historical",
        district: "YSR Kadapa",
        description: "Grand Canyon of India with historic fort",
        imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4a/20/f2/grand-canyon-of-india.jpg?w=1200&h=1200&s=1",
    },
    {
        name: "Pulicat Lake",
        type: "natural",
        district: "Nellore",
        description: "Second largest brackish water lake in India",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMfndgrmVeaRkjOTcaOXswom4bE3xtbChBbA&s",
    },
    {
        name: "Belum Caves",
        type: "natural",
        district: "Kurnool",
        description: "Second longest caves in Indian subcontinent",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Belum_Caves_061.JPG/640px-Belum_Caves_061.JPG",
    },
    {
        name: "Amaravati Stupa",
        type: "historical",
        district: "Guntur",
        description: "Ancient Buddhist site with rich history",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDKOiUXZXt4rpa8mYZK80heF3G1wHDzgneaw&s",
    },
    {
        name: "Konaseema",
        type: "natural",
        district: "East Godavari",
        description: "Beautiful delta region with backwaters",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Prabhalu_Festival.jpg/1200px-Prabhalu_Festival.jpg",
    },
    {
        name: "Horsley Hills",
        type: "natural",
        district: "Chittoor",
        description: "Beautiful hill station with pleasant climate",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0jSYueo-SdsmTLrxSo5DDLP0Jc97lTKtX_g&s",
    },
    {
        name: "Simhachalam Temple",
        type: "religious",
        district: "Visakhapatnam",
        description: "Ancient temple dedicated to Lord Narasimha",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS82_tRSwBRMju8VJyqdL989-QIApCF7aOp2w&s",
    },
    {
        name: "Srisailam Temple",
        type: "religious",
        district: "Kurnool",
        description: "One of the 12 Jyotirlinga temples of Lord Shiva",
        imageUrl: "https://srisailamtourism.com/images/places-to-visit/headers/bhramaramba-devi-temple-srisailam-entry-fee-timings-holidays-reviews-header.jpg",
    },
    {
        name: "RK Beach",
        type: "natural",
        district: "Visakhapatnam",
        description: "Popular beach with submarine museum",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnAyqfU91PLE4S_NDvupQKThnudljbemJsGQ&s",
    },
    {
        name: "Ahobilam",
        type: "religious",
        district: "Kurnool",
        description: "Sacred site with nine temples dedicated to Lord Narasimha",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Upper_Ahobilam_temple_Gopuram_02.jpg",
    },
    {
        name: "Talakona Waterfall",
        type: "natural",
        district: "Chittoor",
        description: "Highest waterfall in Andhra Pradesh",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7MOK1zr8u8slQGW0WudK_7ypuyCbiH6yVcQ&s",
    },
    {
        name: "Bhavani Island",
        type: "natural",
        district: "Krishna",
        description: "River island with recreational facilities",
        imageUrl: "https://media-cdn.tripadvisor.com/media/photo-s/10/22/9c/2e/tree-top-rooms.jpg",
    },
    {
        name: "Kondapalli Fort",
        type: "historical",
        district: "Krishna",
        description: "13th-century fort known for wooden toys",
        imageUrl: "https://s7ap1.scene7.com/is/image/incredibleindia/3-kondapalli-fort-guntur-andhra-pradesh-attr-about?qlt=82&ts=1726743674033",
    },
    {
        name: "Etikoppaka",
        type: "cultural",
        district: "Visakhapatnam",
        description: "Village famous for wooden toy craft",
        imageUrl: "https://lsmedia.linker-cdn.net/282256/2021/7101297.jpeg?width=1200&height=1125",
    },
    {
        name: "Dindi",
        type: "natural",
        district: "East Godavari",
        description: "Scenic backwater destination",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-xXBwqfNOo8F1hW4y4yVzjGBc7B2qKMFZw&s",
    },
    {
        name: "Penchalakona Temple",
        type: "religious",
        district: "Nellore",
        description: "Ancient temple surrounded by seven hills",
        imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/3e/02/19/penchalakona-temple.jpg?w=900&h=500&s=1",
    },
    {
        name: "Coringa Wildlife Sanctuary",
        type: "natural",
        district: "East Godavari",
        description: "Second largest mangrove forest in India",
        imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/71/95/9a/snapseed-01-largejpg.jpg?w=900&h=-1&s=1",
    },
    {
        name: "Sri Kalahasti Temple",
        type: "religious",
        district: "Chittoor",
        description: "Famous temple for Rahu-Ketu prayers",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/Sri_Kala_Hasti.jpg",
    }
];